name: Build ANGLE for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 curl unzip
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings/bazel-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update
          sudo apt-get install -y bazel

      - name: Install Android NDK
        run: |
          mkdir -p ~/android
          cd ~/android
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          echo "export ANDROID_NDK_HOME=~/android/android-ndk-r25b" >> $GITHUB_ENV

      - name: Bootstrap ANGLE
        run: |
          python3 scripts/bootstrap.py
          echo "target_os = ['android']" >> .gclient
          gclient sync

      - name: Configure GN args
        run: |
          mkdir -p out/Android
          echo 'target_os = "android"' > out/Android/args.gn
          echo 'target_cpu = "arm64"' >> out/Android/args.gn
          echo 'is_component_build = false' >> out/Android/args.gn
          echo 'is_debug = false' >> out/Android/args.gn
          echo 'angle_assert_always_on = true' >> out/Android/args.gn

      - name: Build ANGLE
        run: |
          gn gen out/Android
          autoninja -C out/Android angle_apks

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: AngleLibraries.apk
          path: out/Android/apks/AngleLibraries.apk
